# Generated by Django 5.0 on 2024-11-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='student_profile'),
        ),
    ]
